// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// motif_census_uni
NumericMatrix motif_census_uni(LogicalMatrix mat);
RcppExport SEXP _motifcensus_motif_census_uni(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(motif_census_uni(mat));
    return rcpp_result_gen;
END_RCPP
}
// motif_census_bi
NumericMatrix motif_census_bi(LogicalMatrix mat, IntegerMatrix ref);
RcppExport SEXP _motifcensus_motif_census_bi(SEXP matSEXP, SEXP refSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ref(refSEXP);
    rcpp_result_gen = Rcpp::wrap(motif_census_bi(mat, ref));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_motifcensus_motif_census_uni", (DL_FUNC) &_motifcensus_motif_census_uni, 1},
    {"_motifcensus_motif_census_bi", (DL_FUNC) &_motifcensus_motif_census_bi, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_motifcensus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
