# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name motif_census
#'
#' @title Compute motif census for a directional network.
#'
#' @description
#' Count motifs and positions within motifs for a directional network.
#'
#' @param mat a square matrix of logical describing a directional network.
#'
#' @export
#'
#' @return
#' A dataframe with species as rows and motifs as columns, motif positions are ordered as follows:
#'	* 1 linear chains bottom;
#'	* 2 linear chains middle;
#'	* 3 linear chains top;
#'	* 4 apparent competition botton;
#'	* 5 apparent competition top;
#'	* 6 exploitative competition bottom;
#'	* 7 exploitative competition top;
#'	* 8 omnivory bottom;
#'	* 9 omnivory middle;
#'	* 10 omnivory top;
#'	* 11 circular (e.g. 1->2->3->1).
NULL

motif_census <- function(mat) {
    .Call('_motifscensus_motif_census', PACKAGE = 'motifscensus', mat)
}

#' @name motif_census_bidirectional
#'
#' @title Compute motif census for a bidirectional network.
#'
#' @description
#' Count motifs and positions within motifs for a bidirectional network.
#'
#' @param mat a square matrix of logical describing a directional network.
#'
#' @references
#' Milo, R. (2002). Network Motifs: Simple Building Blocks of Complex Networks. Science, 298(5594), 824–827. https://doi.org/10.1126/science.298.5594.824
#'
#' @export
#'
motif_census_bidirectional <- function(mat) {
    .Call('_motifscensus_motif_census_bidirectional', PACKAGE = 'motifscensus', mat)
}

