# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

motif_census_uni <- function(mat) {
    .Call('_motifcensus_motif_census_uni', PACKAGE = 'motifcensus', mat)
}

motif_census_bi <- function(mat, ref) {
    .Call('_motifcensus_motif_census_bi', PACKAGE = 'motifcensus', mat, ref)
}

